Repository kubernetes-sigs/cluster-api-ipam-provider-in-cluster, pull requests merged in 2023-10, with the labels that each got.

#197 🌱 Add `categories=cluster-api` to the crd
  api/v1alpha1/inclusterippool_types.go
  api/v1alpha2/inclusterippool_types.go
  config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#198 🌱 add rikatz to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm

#199 📖 Update readme
  CODEOWNERS
  NOTICE
  README.md
Labels: cncf-cla: yes, size/M, approved, lgtm
