Repository kubernetes-sigs/cluster-api-ipam-provider-in-cluster, pull requests merged in 2024-02, with the labels that each got.

#214 ⚠️ align prefix of deployments with image name
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  tilt-provider.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#228 🌱 Update to current preferred config directory
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#227 🌱 add clusterctl move-hierarchy labels to pools
  config/crd/kustomization.yaml
  config/crd/patches/clusterctl-label_in_globalinclusterippools.yaml
  config/crd/patches/clusterctl-label_in_inclusterippools.yaml
Labels: cncf-cla: yes, size/S, approved

#229 🐛 align image name with other capi providers
  Makefile
Labels: cncf-cla: yes, approved

#230 🌱 align image name even more with other capi providers
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#220 Ensure IPAddress has a ClusterName label as CAPI resources
  internal/controllers/ipaddressclaim_test.go
  pkg/ipamutil/reconciler.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#232 :warning: ReleaseAddress should receive a context
  internal/controllers/ipaddressclaim.go
  pkg/ipamutil/reconciler.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#231 🌱 use registry.k8s.io image in release manifests
  Makefile
  config/default/manager_image_patch.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#234 🐛 fix docker-push-manifest
  Makefile
Labels: cncf-cla: yes, size/XS, approved

#235 🌱 Add mcbenjemaa to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS, approved, lgtm
