Repository kubernetes-sigs/cluster-api-ipam-provider-in-cluster, pull requests merged in 2024-09, with the labels that each got.

#275 ✨ add support for the claim.spec.clusterName property
  config/crd/test/ipam.cluster.x-k8s.io_ipaddressclaims.yaml
  config/crd/test/ipam.cluster.x-k8s.io_ipaddresses.yaml
  go.mod
  go.sum
  internal/controllers/ipaddressclaim.go
  internal/controllers/ipaddressclaim_test.go
  pkg/ipamutil/reconciler.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#284 Make github action able to create a draft release
  .github/workflows/draft_release.yaml
Labels: cncf-cla: yes, size/XS, approved

#288 Allow IPPool to have Prefix /0
  api/v1alpha2/inclusterippool_types.go
  config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
  internal/poolutil/pool_test.go
  internal/webhooks/inclusterippool.go
  internal/webhooks/inclusterippool_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#291 🌱 Add issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release.md
Labels: cncf-cla: yes, kind/documentation, size/M, approved, lgtm
