Repository kubernetes-sigs/cluster-api-ipam-provider-in-cluster, pull requests merged in 2024-05, with the labels that each got.

#250 🌱 update dependencies
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/ipam.cluster.x-k8s.io_globalinclusterippools.yaml
  config/crd/bases/ipam.cluster.x-k8s.io_inclusterippools.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L

#256 🌱 Update conversion-gen to a fixed tag
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#253 🐛 Add reconciler watch for when pool capacity becomes available
  internal/controllers/ipaddressclaim.go
  internal/controllers/ipaddressclaim_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm
